version: '2'
services:
    couchdb:
      image: couchdb:1.6.1
      ports:
        - "5984:5984"
      environment:
        - COUCHDB_USER=admin
        - COUCHDB_PASSWORD=1234qwer

    iotserver:
      image: zyfdedh/iot-server:dev
      ports:
        - "3000:3000"
      environment:
        - NODE_ENV=production
        - IOT_SERVER_PORT=3000
        - REPOSITORY=https://192.168.10.187:5000
#        - SECRET=linkeriot@linkernetworks
#        - WEB_NONCE=linkeriot@forportal
#        - WEB_SECRET=3a8ef67d5ad4fb0ab4ef382006d337470c7fb53b0c434742b93fddb92e0dab54
        - IOT_COUCHDB=192.168.10.187
      depends_on:
        - couchdb

    dockerauth:
      image: zyfdedh/docker_auth
      ports:
        - "5001:5001"
      volumes:
        - "./config:/config:ro"
        - "./logs:/logs:rw"
        - "./ssl:/ssl:ro"
      command: --v=2 --alsologtostderr /config/auth_config.yml
      depends_on:
        - iotserver
        - registry
      environment:
        - AUTH_API_ENDPOINT=192.168.10.187:3000

    registry:
      image: registry:2
      ports:
        - "5000:5000"
      volumes:
        - "./ssl:/ssl:ro"
        - "./registry/data:/var/lib/registry:rw"
        - "./registry/conf:/etc/docker/registry:ro"

